name: CI Main
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  common:
    uses: Aahil684/github-actions-reusable/.github/workflows/ci-main.yml
    with:
      component_name: frontend
      app_type: nginx